<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bunch</string>
		<string>bunchsnippet</string>
	</array>
	<key>name</key>
	<string>Bunch</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hideall</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#app</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#frontmatter</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>app</key>
		<dict>
			<key>begin</key>
			<string>(!{1,3})?([|@%]*)(?=[\w@])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.negation.bunch</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.bunch</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match an application and its modifiers</string>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>_</string>
					<key>name</key>
					<string>keyword.operator.modifier.bunch</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#delay</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>we have look forwards here to not match the delay or comments at the end of a line</string>
					<key>match</key>
					<string>(.*?)\s*(?=[_~#?]|//|$)</string>
					<key>name</key>
					<string>entity.name.function.app.bunch</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?&lt;!\S)(?=#)(?!#\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>match comments starting with #</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>#</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.bunch</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.number-sign.bunch</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(^[ \t]+)?(?&lt;!\S)(?=//)(?!//\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>match comments starting with //</string>
					<key>end</key>
					<string>(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>//</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>punctuation.definition.comment.bunch</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\n</string>
							<key>name</key>
							<string>comment.line.double-slash.bunch</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>This matches single or multi-line C-style comments like /* my comment */</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.bunch</string>
				</dict>
			</array>
		</dict>
		<key>delay</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>~\d+</string>
					<key>name</key>
					<string>keyword.operator.delay.bunch</string>
				</dict>
			</array>
		</dict>
		<key>frontmatter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(---)\s*$</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.frontmatter.bunch</string>
						</dict>
					</dict>
					<key>end</key>
					<string>^(---)\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.frontmatter.bunch</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.frontmatter.bunch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.key.frontmatter.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.single.bunch</string>
								</dict>
							</dict>
							<key>match</key>
							<string>^(\S[\w ]+)(:)\s*(.*?)$</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>hideall</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^@@</string>
					<key>name</key>
					<string>keyword.operator.hideall.bunch</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>"(.*?)"</string>
					<key>name</key>
					<string>string.quoted.double.bunch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'(.*?)'</string>
					<key>name</key>
					<string>string.quoted.single.bunch</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bunch</string>
	<key>uuid</key>
	<string>8CEF7241-BE3B-49BF-966C-68DCA9E01C43</string>
</dict>
</plist>
